version: '2'

services:
  local-rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "local-rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "8080:15672"
      - "5672:5672"